#******************************************
# Author: Fritz Ammon
# Date: 4 September 2014
# Description: The makefile for project2b.
#******************************************

p2b : project2b.o
	gcc -o p2b project2b.o
project2b.o : project2b.c
	gcc -c project2b.c
clean :
	rm *.o
