#******************************************
# Author: Fritz Ammon
# Date: 4 September 2014
# Description: The makefile for project2a.
#******************************************

p2a : project2a.o
	gcc -o p2a project2a.o
project2a.o : project2a.c
	gcc -c project2a.c
clean :
	rm *.o
